#!/usr/bin/env bash
# Install nigenx , configures and using sed, and starts the server and redirect to another page.

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
echo 'Hello World!' > /var/www/html/index.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
service nginx restart
