#!/usr/bin/env bash
#script printing Best School 10 times using while loop in the 9th also say Hi

counter=1
while [ $counter -le 10 ]
do
	echo "Best School"
	if [ $counter -eq 9 ]
	then
		echo "Hi"
	fi
	counter=$((counter + 1))
done
